CREATE TABLE IF NOT EXISTS logins_users
(id INTEGER AUTO_INCREMENT,
 user_id VARCHAR(50) NOT NULL,
 login_at TIMESTAMP NOT NULL,
 PRIMARY KEY (id));

--;;

CREATE TABLE IF NOT EXISTS logins_companies
(id INTEGER AUTO_INCREMENT,
 company_id VARCHAR(50) NOT NULL,
 login_at TIMESTAMP NOT NULL,
 PRIMARY KEY (id));
