CREATE TABLE IF NOT EXISTS industries
(id INTEGER AUTO_INCREMENT,
 industry VARCHAR(100) NOT NULL,
 PRIMARY KEY (id),
 KEY index_industry (industry));

--;;

INSERT INTO industries VALUES
(1, 'Makine-İmalat'),
(2, 'Turizm'),
(3, 'Otomotiv'),
(4, 'Plastik'),
(5, 'Lojistik'),
(6, 'Bilişim/Yazılım'),
(7, 'Bilişim/Donanım'),
(8, 'Bilişim/Internet'),
(9, 'Bilişim/Servis'),
(10, 'Bilişim/Tasarım'),
(11, 'Madencilik'),
(12, 'Mobilya'),
(13, 'Tekstil'),
(14, 'Tarım ve Hayvancılık'),
(15, 'İnşaat'),
(16, 'Eğitim'),
(17, 'Sağlık'),
(18, 'Gıda'),
(19, 'Enerji'),
(20, 'Kimya'),
(21, 'Basım Yayın Medya'),
(22, 'Ağaç Ürünleri'),
(23, 'Metal Ürünler'),
(24, 'Ambalaj'),
(25, 'Telekomünikasyon'),
(26, 'Hizmet'),
(27, 'Savunma Sanayi'),
(28, 'Finans'),
(29, 'Ulaşım'),
(30, 'İmalat'),
(31, 'Sigortacılık'),
(32, 'Elektrik - Elektronik'),
(33, 'Perakende'),
(34, 'Reklam'),
(35, 'Havacılık ve Hava Taşımacılığı'),
(36, 'Sanat'),
(37, 'Denizcilik'),
(38, 'Eğitim'),
(39, 'İnsan Kaynakları'),
(40, 'Moda ve Tasarım'),
(41, 'Eğlence'),
(42, 'Kamu'),
(43, 'Hukuk'),
(44, 'Görsel Tasarım'),
(45, 'Askeri'),
(46, 'Petrol ve Petrol Ürünleri'),
(47, 'Eczacılık'),
(48, 'Fotoğrafçılık'),
(49, 'Halkla İlişkiler ve İletişim'),
(50, 'Emlak'),
(51, 'Güvenlik'),
(52, 'Satış'),
(53, 'Spor ve Sağlıklı Yaşam');
