CREATE TABLE IF NOT EXISTS pass_reminders
(id INTEGER AUTO_INCREMENT,
 email VARCHAR(100) NOT NULL,
 reminder_code VARCHAR(50) NOT NULL,
 link_expired BOOLEAN DEFAULT FALSE,
 is_sent BOOLEAN DEFAULT FALSE,
 is_used BOOLEAN DEFAULT FALSE,
 created_at TIMESTAMP,
 sent_at TIMESTAMP NULL,
 used_at TIMESTAMP NULL,
 PRIMARY KEY (id));
