CREATE TABLE IF NOT EXISTS locations
(id INTEGER AUTO_INCREMENT,
 location VARCHAR(100) NOT NULL,
 is_boosted BOOLEAN DEFAULT FALSE,
 PRIMARY KEY (id),
 KEY index_location (location));

--;;

INSERT INTO locations VALUES
(1, 'Adana', true),
(2, 'Adıyaman', false),
(3, 'Afyon', false),
(4, 'Ağrı', false),
(5, 'Amasya', false),
(6, 'Ankara', true),
(7, 'Antalya', false),
(8, 'Artvin', false),
(9, 'Aydın', false),
(10, 'Balıkesir', false),
(11, 'Bilecik', false),
(12, 'Bingöl', false),
(13, 'Bitlis', false),
(14, 'Bolu', false),
(15, 'Burdur', false),
(16, 'Bursa', true),
(17, 'Çanakkale', false),
(18, 'Çankırı', false),
(19, 'Çorum', false),
(20, 'Denizli', false),
(21, 'Diyarbakır', false),
(22, 'Edirne', false),
(23, 'Elazığ', false),
(24, 'Erzincan', false),
(25, 'Erzurum', false),
(26, 'Eskişehir', false),
(27, 'Gaziantep', false),
(28, 'Giresun', false),
(29, 'Gümüşhane', false),
(30, 'Hakkari', false),
(31, 'Hatay', false),
(32, 'Isparta', false),
(33, 'İçel', false),
(34, 'İstanbul (Tümü)', true),
(35, 'İzmir', true),
(36, 'Kars', false),
(37, 'Kastamonu', false),
(38, 'Kayseri', false),
(39, 'Kırklareli', false),
(40, 'Kırşehir', false),
(41, 'Kocaeli', true),
(42, 'Konya', false),
(43, 'Kütahya', false),
(44, 'Malatya', false),
(45, 'Manisa', false),
(46, 'Kahramanmaraş', false),
(47, 'Mardin', false),
(48, 'Muğla', false),
(49, 'Muş', false),
(50, 'Nevşehir', false),
(51, 'Niğde', false),
(52, 'Ordu', false),
(53, 'Rize', false),
(54, 'Sakarya', true),
(55, 'Samsun', false),
(56, 'Siirt', false),
(57, 'Sinop', false),
(58, 'Sivas', false),
(59, 'Tekirdağ', false),
(60, 'Tokat', false),
(61, 'Trabzon', false),
(62, 'Tunceli', false),
(63, 'Şanlıurfa', false),
(64, 'Uşak', false),
(65, 'Van', false),
(66, 'Yozgat', false),
(67, 'Zonguldak', false),
(68, 'Aksaray', false),
(69, 'Bayburt', false),
(70, 'Karaman', false),
(71, 'Kırıkkale', false),
(72, 'Batman', false),
(73, 'Şırnak', false),
(74, 'Bartın', false),
(75, 'Ardahan', false),
(76, 'Iğdır', false),
(77, 'Yalova', false),
(78, 'Karabük', false),
(79, 'Kilis', false),
(80, 'Osmaniye', false),
(81, 'Düzce', false),
(82, 'İstanbul, Anadolu Yakası', true),
(83, 'İstanbul, Avrupa Yakası', true);
