CREATE TABLE IF NOT EXISTS offers
(id INTEGER AUTO_INCREMENT,
 job_id VARCHAR(50) NOT NULL,
 user_id VARCHAR(50) NOT NULL,
 is_push_sent BOOLEAN DEFAULT FALSE,
 is_email_sent BOOLEAN DEFAULT FALSE,
 is_seen BOOLEAN DEFAULT FALSE,
 is_chatted BOOLEAN DEFAULT FALSE,
 is_applied BOOLEAN DEFAULT FALSE,
 is_favorited BOOLEAN DEFAULT FALSE,
 is_referred BOOLEAN DEFAULT FALSE,
 is_expired BOOLEAN DEFAULT FALSE,
 created_at TIMESTAMP,
 push_sent_at TIMESTAMP NULL,
 email_sent_at TIMESTAMP NULL,
 seen_at TIMESTAMP NULL,
 chatted_at TIMESTAMP NULL,
 applied_at TIMESTAMP NULL,
 favorited_at TIMESTAMP NULL,
 referred_at TIMESTAMP NULL,
 PRIMARY KEY (id),
 KEY index_user_created_at (user_id, created_at),
 KEY index_user_seen (user_id, is_seen),
 KEY index_user_job (user_id, job_id),
 KEY index_job_created (job_id, created_at));
